# Generated by Django 5.0.1 on 2024-01-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('kurs', models.PositiveSmallIntegerField()),
                ('Student_raqami', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=40)),
                ('sana', models.DateField()),
                ('batafsil_malumot', models.CharField(blank=True, max_length=100, null=True)),
                ('bajarilgan', models.BooleanField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ombor.student')),
            ],
        ),
    ]
